---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Modules overlay & br_netfilter for persistance
  blockinfile:
    state: present
    create: yes
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Enable overlay module
  modprobe:
    name: overlay
    state: present

- name: Enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: UnHold containerd.io
  command: >
      apt-mark unhold containerd.io
  ignore_errors: True

- name: Update apt and install containerd.io
  apt:
    update_cache: yes
    state: present
    force: true
    name: '{{ item }}'
  loop: [ 'containerd.io' ]

- name: Hold containerd.io
  command: >
      apt-mark hold containerd.io
  ignore_errors: True

- name: Set containerd.sock for crictl
  lineinfile:
    state: present
    create: yes
    path: /etc/crictl.yaml
    line: 'runtime-endpoint: unix:///run/containerd/containerd.sock'

- name: Enable containerd to boot on start
  service:
    name: containerd
    enabled: true
    state: started

- name: Copy /etc/containerd/config.toml
  template:
    src: config-{{ node_type }}.toml
    dest: /etc/containerd/config.toml
    mode: 0644
    owner: root
    group: root
  notify: restart containerd
